include(InstallRequiredSystemLibraries)

set(CPACK_PACKAGE_NAME "print")
set(CPACK_PACKAGE_VENDOR "solyuway")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Static C++ library for printing and solver application")
set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/DESCRIPTION")

set(CPACK_PACKAGE_VERSION_MAJOR "${PRINT_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${PRINT_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${PRINT_VERSION_PATCH}")
set(CPACK_PACKAGE_VERSION_TWEAK "${PRINT_VERSION_TWEAK}")
set(CPACK_PACKAGE_VERSION "${PRINT_VERSION}")

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

set(CPACK_RPM_PACKAGE_NAME "print-devel")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_GROUP "Development/Libraries")
set(CPACK_RPM_PACKAGE_RELEASE 1)

set(CPACK_DEBIAN_PACKAGE_NAME "libprint-dev")
set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "Static C++ library for printing and solver")
set(CPACK_DEBIAN_PACKAGE_SECTION "libs")
set(CPACK_DEBIAN_PACKAGE_RELEASE 1)

set(CPACK_DMG_VOLUME_NAME "Print Library ${PRINT_VERSION}")

set(CPACK_GENERATOR "TGZ;ZIP")

include(CPack)
