include(InstallRequiredSystemLibraries)

set(CPACK_PACKAGE_NAME "print")
set(CPACK_PACKAGE_VENDOR "${GITHUB_USERNAME}")
set(CPACK_PACKAGE_CONTACT "${GITHUB_EMAIL}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Static C++ library for printing")
set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/DESCRIPTION")

set(CPACK_PACKAGE_VERSION_MAJOR "${PRINT_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${PRINT_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${PRINT_VERSION_PATCH}")
set(CPACK_PACKAGE_VERSION_TWEAK "${PRINT_VERSION_TWEAK}")
set(CPACK_PACKAGE_VERSION "${PRINT_VERSION}")

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

set(CPACK_RPM_PACKAGE_NAME "print-devel")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_GROUP "Development/Libraries")
set(CPACK_RPM_PACKAGE_RELEASE 1)
set(CPACK_RPM_CHANGELOG_FILE "${CMAKE_CURRENT_SOURCE_DIR}/ChangeLog.md")

set(CPACK_DEBIAN_PACKAGE_NAME "libprint-dev")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${GITHUB_EMAIL}")
set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "Static C++ library for printing")
set(CPACK_DEBIAN_PACKAGE_SECTION "libs")
set(CPACK_DEBIAN_PACKAGE_RELEASE 1)

set(CPACK_DMG_VOLUME_NAME "Print Library ${PRINT_VERSION}")

set(CPACK_WIX_UPGRADE_GUID "12345678-1234-1234-1234-123456789012")
set(CPACK_WIX_PRODUCT_GUID "87654321-4321-4321-4321-210987654321")

set(CPACK_GENERATOR "TGZ;ZIP")

include(CPack)

# Настройки для WiX (MSI)
set(CPACK_WIX_LICENSE_RTF "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE.rtf")
set(CPACK_WIX_PRODUCT_GUID "12345678-1234-1234-1234-123456789012")
set(CPACK_WIX_UPGRADE_GUID "87654321-4321-4321-4321-210987654321")
set(CPACK_WIX_MONO_CULTURE "en-US")
